name: bump

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4

      - name: Verify tags
        run: git tag
