name: bump

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Verify tags
        run: git tag
